config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :reviews
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews

  validates :name, :image, :cost, :description, :star, :agency, :craft, :distance, presence: true
  validates :cost, numericality: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :author, :content, :rating, presence: true
  validates :content, length: { in: 10..250 }
  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :nullify
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authorize
    if !current_user
      flash[:alert] = "Please sign in (or up) to visit that page."
      redirect_to '/'
    end
  end

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def admin_authorize
    if !current_user || current_user.admin == false
      flash[:alert] = "Only administrators can visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :admin_authorize, only: [:new, :create, :edit, :update, :destroy]

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product has been added"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product has been updated"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Product has been removed"
      redirect_to products_path
    end
  end


private
  def product_params
    params.require(:product).permit(:name, :cost, :image, :description, :star, :agency, :craft, :distance)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, except: [:show, :index]
  before_action :admin_authorize, only: [:destroy]

  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(reviews_params)
    @review.user_id = current_user.id
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def update
    @product= Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(reviews_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully destroyed!"
    redirect_to product_path(@review.product)
  end


private
  def reviews_params
    params.require(:review).permit(:author, :content, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # helper_method :is_admin?
  #
  # def is_admin?
  #   current_user && current_user.admin
  # end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Subrayada:400,700|Orbitron:400,500|Yanone+Kaffeesatz:300" rel="stylesheet">
  </head>

  <body>
    <%= link_to "home", '/' %> |
    <% if current_user %>
      <%= current_user.email %> | <%= link_to "sign out", '/signout' %>
    <% else %>
      <%= link_to "sign in", '/signin' %> | <%= link_to "sign up", 'signup' %>
    <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<br>
<%= render "layouts/errors", :object => @product %>
<br>
<div class="form_container">
  <%= form_for @product do |f| %>
  <div class="row">
    <div class="col-md-3">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="col-md-3">
      <%= f.label :cost %>
      <%= f.text_field :cost %>
    </div>
    <div class="col-md-3">
      <%= f.label :image %>
      <%= f.text_field :image %>
    </div>
    <div class="col-md-3">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <%= f.label :craft %>
      <%= f.text_field :craft %>
    </div>
    <div class="col-md-3">
      <%= f.label :star %>
      <%= f.text_field :star %>
    </div>
    <div class="col-md-3">
      <%= f.label :agency %>
      <%= f.text_field :agency %>
    </div>
    <div class="col-md-3">
      <%= f.label :distance %>
      <%= f.text_field :distance %>
    </div>
  </div>
  <br>
  <br>
  <div class="form_submit_button">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editting <%= @product.name %></h1>

<%= render "form" %>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1>Space Trips</h1>
  <p>shoot for the moon and let your next vacation be out of this world</p>
</div>

<div class="row">
  <div class="col-md-8">
    <h3>All Trips</h3>
    <% if current_user && current_user.admin == true %>
      <p><%= link_to "Add a New Trip", new_product_path %></p>
    <% end %>
    <ul class="all_products">
      <% @products.each do |product| %>
        <li><%= link_to product.name, product_path(product)%>, <%= product.cost %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/products/new.html.erb
<h1>Add a New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<%= image_tag("#{@product.image}") %>
<p><%= @product.cost %></p>
<p>Travel <%= @product.distance %> in the luxurious <%= @product.craft %> with the esteemed <%= @product.agency %> to the lovely <%= @product.name %>.</p>
<p> You'll see unbelievable sights like <%= @product.description %>! You'll want to bring a camera to capture a selfie near <%= @product.star %>. This is good old fashioned family fun, but in space!

<% if current_user && current_user.admin == true %>
  <p><%= link_to "Edit This Trip", edit_product_path(@product) %></p>
  <p><%= link_to "Remove this Trip", product_path(@product),
                            :data => {
                            :confirm => "You sure?",
                            :method => "delete"} %></p>
<% end %>

<h3>What others have said about this trip:</h3>
<% if current_user == current_user %>
  <p><%= link_to "Review this Trip", new_product_review_path(@product) %></p>
<% end %>
<% if @product.reviews.any? %>
  <ul>
    <% @product.reviews.each do |review| %>
    <p>Reviewed by: <%= review.author %></p>
    <p>Rating: <%= review.rating %></p>
    <p><%= review.content %></p>
    <% if current_user && current_user.id == review.user_id  %>
      <%= link_to "Edit Review", edit_product_review_path(@product, review) %>
    <% end %>
    <% if current_user && current_user == review.user_id || current_user && current_user.admin == true %>
      <%= link_to "Delete Review", product_review_path(@product, review),
      :data => {:confirm => "Are you sure?",
      :method => "delete"} %>
    <% end %>
    <br>
  <%end%>
  </ul>
<% else %>
  <p>This trip hasn't been reviewed yet</p>
<% end %>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [ @product, @review ] do |f| %>
  <%= f.label :author%>
  <%= f.text_field :author %>
  <%= f.label :content%>
  <%= f.text_area :content %>
  <%= f.label :rating %>
  <%= f.select :rating, ['1', '2', '3', '4', '5'] %>

  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h2>Edit your comment:</h2>
<%= render "form" %>

app/views/reviews/new.html.erb
<h2>Add your review"</h2>
<%= render "form" %>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= render "layouts/errors", :object => @user %>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.email_field :email, id: "email" %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>